name: user_repository
description: "Package which manages the user domain."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  domain_models:
    path: ../domain_models
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.2
  key_value_storage:
    path: ../key_value_storage
  rxdart: ^0.28.0
  trust_cafe_api:
    path: ../trust_cafe_api

dev_dependencies:
  flutter_lints: ^6.0.0