name: post
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  bloc: ^8.1.4
  content_repository:
    path: ../../content_repository
  component_library:
    path: ../../component_library
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  flutter:
    sdk: flutter
  domain_models:
    path: ../../domain_models
  user_repository:
    path: ../../user_repository
  userprofile:
    path: ../userprofile
  spider:
    path: ../spider
  text_editor:
    path: ../text_editor
  branch:
    path: ../branch
  branches:
    path: ../branches
  trust:
    path: ../trust
  comments:
    path: ../comments

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  test: ^1.26.2
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true