name: content_repository
description: "Package which manages the content domain."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  domain_models:
    path: ../domain_models
  equatable: ^2.0.7
  key_value_storage:
    path: ../key_value_storage
  trust_cafe_api:
    path: ../trust_cafe_api
  rxdart: ^0.28.0
  translator: ^1.0.3+1
  html: ^0.15.5
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_lints: ^6.0.0