name: trust_cafe_api
description: "Package to interact with TrustCafe API."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.7
  http: ^1.2.2
  json_annotation: ^4.9.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.13
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.9.0
  mockito: ^5.4.4
  lints: ^5.0.0
  test: ^1.25.8


