name: key_value_storage
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  hive_ce: ^2.11.4
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.7.1
  hive_ce_generator: 1.9.3
  flutter_lints: ^6.0.0
  test: ^1.26.2