name: key_value_storage
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  hive: 2.2.3
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.13
  hive_generator: 2.0.1
  lints: ^5.0.0
  test: ^1.24.3