name: spider
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  component_library:
    path: ../../component_library
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  flutter:
    sdk: flutter
  domain_models:
    path: ../../domain_models
  content_repository:
    path: ../../content_repository
  user_repository:
    path: ../../user_repository
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  test: ^1.25.7
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true