name: domain_models
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  equatable: ^2.0.7

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.26.2