name: component_library
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
#  flutter_widget_from_html: ^0.14.11
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.4.1
  easy_image_viewer: ^1.5.1
  html: ^0.15.4
  domain_models:
    path: ../domain_models

  flutter_widget_from_html: ^0.15.2
  flutter_svg: ^2.0.10+1
  infinite_scroll_pagination: ^4.0.0
  carousel_slider: ^5.0.0
  super_clipboard: ^0.8.20
  flutter_cache_manager: ^3.3.2
  gal: ^2.3.0
  url_launcher: ^6.3.0
  http: ^1.2.2
  routemaster: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.3
  test: ^1.24.9
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true