name: settings
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  bloc: ^8.1.4
  component_library:
    path: ../../component_library
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  flutter:
    sdk: flutter
  domain_models:
    path: ../../domain_models
  user_repository:
    path: ../../user_repository
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  test: ^1.26.2
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true