name: trust_cafe_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.3.0+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  content_repository:
    path: packages/content_repository
  changes:
    path: packages/features/changes
  comment:
    path: packages/features/comment
  comments:
    path: packages/features/comments
  component_library:
    path: packages/component_library
  auth:
    path: packages/features/auth
  home:
    path: packages/features/home
  settings:
    path: packages/features/settings
  post:
    path: packages/features/post
  trust:
    path: packages/features/trust
  text_editor:
    path: packages/features/text_editor
  spider:
    path: packages/features/spider
  branches:
    path: packages/features/branches
  feed:
    path: packages/features/feed
  flutter:
    sdk: flutter
  routemaster: ^1.0.1
  shared_preferences: ^2.2.3
  user_repository:
    path: packages/user_repository
  trust_cafe_api:
    path: packages/trust_cafe_api
  key_value_storage:
    path: packages/key_value_storage
  domain_models:
    path: packages/domain_models

  flutter_quill_extensions: ^10.8.1

  go_router: ^14.2.0

dependency_overrides:
  webview_flutter_android: 3.16.1
  chewie: ^1.8.1
  win32: ^5.5.3
#  file_picker:
#    git:
#      url: https://github.com/melWiss/flutter_file_picker.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  image_path: "assets/appicon_legacy.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/appicon.png"
  adaptive_icon_monochrome: "assets/appicon_monochrome.png"
  adaptive_icon_foreground_inset: 22

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/reactions/
    - shorebird.yaml
