name: home
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  content_repository:
    path: ../../content_repository
  component_library:
    path: ../../component_library
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  flutter:
    sdk: flutter
  domain_models:
    path: ../../domain_models
  user_repository:
    path: ../../user_repository
  feed:
    path: ../feed
  text_editor:
    path: ../text_editor
  infinite_scroll_pagination: ^4.0.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.3
  test: ^1.24.9
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true