name: home
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  bloc: ^8.1.4
  content_repository:
    path: ../../content_repository
  component_library:
    path: ../../component_library
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  flutter:
    sdk: flutter
  domain_models:
    path: ../../domain_models
  user_repository:
    path: ../../user_repository
  feed:
    path: ../feed
  text_editor:
    path: ../text_editor
  infinite_scroll_pagination: ^4.1.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  test: ^1.25.7
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true