name: component_library
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  easy_image_viewer: ^1.5.1
  html: ^0.15.5
  flutter_widget_from_html_core: ^0.15.2
  flutter_svg: ^2.0.10+1
  infinite_scroll_pagination: ^4.1.0
  carousel_slider: ^5.0.0
  flutter_cache_manager: ^3.4.1
  gal: ^2.3.0
  url_launcher: ^6.3.1
  http: ^1.2.2
  routemaster: ^1.0.1
  quill_native_bridge: ^11.1.0

  domain_models:
    path: ../domain_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.26.2
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true