name: Build and Release apk

permissions:
  contents: write

on:
  push:
    branches:
      - demo
      - main

jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v1
        with:
          channel: stable
          flutter-version: '3.35.3'

      - name: Set up Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: Update version in pubspec.yaml
        id: update_version
        run: |
          version_line=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f2)
          version_name=$(echo $version_line | cut -d+ -f1)

          version_code=$((10000 + $GITHUB_RUN_NUMBER))

          sed -i "s/^version: .*/version: ${version_name}+${version_code}/" pubspec.yaml

          echo "VERSION_NAME=$version_name" >> $GITHUB_ENV
          echo "VERSION_CODE=$version_code" >> $GITHUB_ENV
          echo "VERSION=${version_name}+${version_code}" >> $GITHUB_ENV

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle
        run: flutter build appbundle

      - name: Rename artifacts
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-${VERSION_NAME}+${VERSION_CODE}.apk
          mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/app-${VERSION_NAME}+${VERSION_CODE}.aab

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}.apk
          path: build/app/outputs/flutter-apk/app-${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}.aab
          path: build/app/outputs/bundle/release/app-${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}.aab

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}.apk,build/app/outputs/bundle/release/app-${{ env.VERSION_NAME }}+${{ env.VERSION_CODE }}.aab"
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
